FROM ubuntu:trusty

EXPOSE 4000

ENV NODE_MODULES /usr/local/lib/node_modules/
ENV DISPLAY :99.0

RUN apt-get -y update && apt-get install -y \
redis-server \
rabbitmq-server \
git \
wget \
curl \
unzip \
default-jre \
libmysqlclient-dev \
libxml2-dev \
libxslt-dev \
libjpeg-dev \
libfreetype6-dev \
libtiff-dev \
libffi-dev \
libssl-dev \
software-properties-common \
python-dev \
python-pip \
# Only for testing
chromium-browser \
libblas-dev \
liblapack-dev \
gfortran \
imagemagick \
xpdf

# Download nodejs
RUN curl -sL https://deb.nodesource.com/setup_5.x | bash - && \
apt-get install -y nodejs

# Download ElasticSearch
ENV ES_VERSION 2.1.1
RUN wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-"${ES_VERSION}".zip && \
    unzip elasticsearch-"${ES_VERSION}".zip && \
    rm elasticsearch-"${ES_VERSION}".zip && \
    cd elasticsearch-"${ES_VERSION}" && \
    bin/plugin install analysis-icu && \
    bin/plugin install org.codelibs/elasticsearch-reindexing/"${ES_VERSION}"

# Download chromedriver
ENV CHROMEDRIVER_VERSION 2.21
RUN wget http://chromedriver.storage.googleapis.com/"${CHROMEDRIVER_VERSION}"/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod 755 /usr/bin/chromedriver

# Configure and install MySQL
ENV MYSQL_VERSION 5.6
RUN { \
    echo mysql-community-server mysql-community-server/data-dir select ''; \
    echo mysql-community-server mysql-community-server/root-pass password ''; \
    echo mysql-community-server mysql-community-server/re-root-pass password ''; \
    echo mysql-community-server mysql-community-server/remove-test-db select false; \
} | debconf-set-selections
RUN apt-get install -y mysql-server-"${MYSQL_VERSION}"

# NPM dependencies (installed in /usr/local/bin)
RUN npm update && npm install -g bower less clean-css uglify-js requirejs

# Beard
RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install scipy
RUN pip install git+https://github.com/inveniosoftware/beard@master#egg=beard

# Invenio
RUN mkdir /src && cd /src/ && \
    git clone --branch=labs https://github.com/inspirehep/invenio.git && \
    cd invenio && pip install -e .

# Final setup
RUN groupadd -r elasticsearch && useradd -r -g elasticsearch elasticsearch
RUN chown -R elasticsearch:elasticsearch /elasticsearch-"${ES_VERSION}"
