FROM ubuntu:trusty

EXPOSE 4000

ENV ES_VERSION 1.7.1
ENV MYSQL_VERSION 5.6
ENV NODE_MODULES /usr/local/lib/node_modules/

RUN apt-get -y update && apt-get install -y \
redis-server \
git \
wget \
curl \
unzip \
nodejs \
npm \
default-jre \
libmysqlclient-dev \
libxml2-dev \
libxslt-dev \
libjpeg-dev \
libfreetype6-dev \
libtiff-dev \
libffi-dev \
software-properties-common \
python-dev \
python-pip\
ibblas-dev \
liblapack-dev \
gfortran \
imagemagick

# Download and run ElasticSearch
RUN wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-"${ES_VERSION}".zip && \
    unzip elasticsearch-"${ES_VERSION}".zip && \
    rm elasticsearch-"${ES_VERSION}".zip

# For the new Nodejs to work
RUN ln -s /usr/bin/nodejs /usr/bin/node

# Configure and install MySQL
RUN { \
    echo mysql-community-server mysql-community-server/data-dir select ''; \
    echo mysql-community-server mysql-community-server/root-pass password ''; \
    echo mysql-community-server mysql-community-server/re-root-pass password ''; \
    echo mysql-community-server mysql-community-server/remove-test-db select false; \
} | debconf-set-selections
RUN apt-get install -y mysql-server-"${MYSQL_VERSION}"

# NPM dependencies (installed in /usr/local/bin)
RUN npm update && npm install -g bower less clean-css uglify-js requirejs

# Beard
RUN pip install git+https://github.com/inveniosoftware/beard@master#egg=beard

# Invenio
RUN mkdir /src && \
    cd /src/ && \
    git clone --branch=master https://github.com/inspirehep/invenio.git && \
    cd invenio && \
    pip install -e .

# INSPIRE
RUN cd /src/ && \
    git clone --branch=master https://github.com/inspirehep/inspire-next.git && \
    cd inspire-next && \
    pip install -e .

# Install Bower dependencies
RUN cd /src/inspire-next && \
    inveniomanage bower -i bower-base.json > bower.json && \
    bower install --force-latest --allow-root

# Configuration
RUN inveniomanage config create secret-key && \
    inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail && \
    inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami` && \
    inveniomanage config set CFG_TMPDIR /tmp && \
    inveniomanage config set CFG_SITE_URL http://0.0.0.0:4000 && \
    inveniomanage config set CFG_SITE_SECURE_URL https://0.0.0.0:4000
# assets build?

# Set NPM deps binaries
RUN inveniomanage config set LESS_BIN `find $NODE_MODULES -iname lessc | head -1` && \
    inveniomanage config set CLEANCSS_BIN `find $NODE_MODULES -iname cleancss | head -1` && \
    inveniomanage config set REQUIREJS_BIN `find $NODE_MODULES -iname r.js | head -1` && \
    inveniomanage config set UGLIFYJS_BIN `find $NODE_MODULES -iname uglifyjs | head -1`

RUN inveniomanage collect > /dev/null

# Database
RUN service mysql start && \
    service redis-server start && \
    (./elasticsearch-"${ES_VERSION}"/bin/elasticsearch &) && \
    sleep 7 && \
    inveniomanage database init --user=root --password= --yes-i-know && \
    inveniomanage database create --quiet && \
    inveniomanage records create -t marcxml /src/inspire-next/inspire/demosite/data/demo-records.xml > /dev/null 2>&1

CMD service mysql start && \
    service redis-server start && \
    service rabbitmq-server start && \
    (celery worker -E -A invenio.celery.celery --loglevel=INFO --workdir=$VIRTUAL_ENV 1> /dev/null &) && \
    (./elasticsearch-"${ES_VERSION}"/bin/elasticsearch &) && \
    sleep 7 && \
    inveniomanage runserver -h 0.0.0.0 -p 4000 -R

# TODO replace CMD with `CMD honcho start`
