FROM inspirehep/inspire:deps

EXPOSE 4000

ENV ES_VERSION 1.7.1
ENV MYSQL_VERSION 5.6
ENV NODE_MODULES /usr/local/lib/node_modules/
ENV DISPLAY :99.0

# INSPIRE
RUN cd /src/ && \
    git clone --branch=master https://github.com/inspirehep/inspire-next.git && \
    cd inspire-next && \
    pip install -r requirements.txt

RUN pip install Flask-DebugToolbar==0.9.0

# Install Bower dependencies
RUN cd /src/inspire-next && \
    inveniomanage bower -i bower-base.json > bower.json && \
    bower install --force-latest --allow-root

# Configuration
RUN inveniomanage config create secret-key && \
    inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail && \
    inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami` && \
    inveniomanage config set CFG_TMPDIR /tmp && \
    inveniomanage config set DEBUG True && \
    inveniomanage config set DEBUG_TB_ENABLED False && \
    inveniomanage config set CFG_SITE_URL http://0.0.0.0:4000
# assets build?

# Set NPM deps binaries
RUN inveniomanage config set LESS_BIN `find $NODE_MODULES -iname lessc | head -1` && \
    inveniomanage config set CLEANCSS_BIN `find $NODE_MODULES -iname cleancss | head -1` && \
    inveniomanage config set REQUIREJS_BIN `find $NODE_MODULES -iname r.js | head -1` && \
    inveniomanage config set UGLIFYJS_BIN `find $NODE_MODULES -iname uglifyjs | head -1`

RUN inveniomanage collect > /dev/null

RUN inveniomanage assets build --no-cache --production

RUN pip install watchdog==0.8.3

# Database
RUN service mysql start && \
    service redis-server start && \
    service rabbitmq-server start && \
    (celery worker -E -A invenio.celery.celery --loglevel=INFO --workdir=$VIRTUAL_ENV 1> /dev/null &) && \
    (./elasticsearch-"${ES_VERSION}"/bin/elasticsearch &) && \
    sleep 7 && \
    inveniomanage database init --user=root --password= --yes-i-know && \
    inveniomanage database create --quiet && \
    inveniomanage records create -t marcxml /src/inspire-next/inspire/demosite/data/demo-records.xml

CMD service mysql start && \
    service redis-server start && \
    service rabbitmq-server start && \
    (/elasticsearch-"${ES_VERSION}"/bin/elasticsearch &) && \
    cd /src/inspire-next && \
    pip install -e . && \
    (celery worker -E -A invenio.celery.celery --loglevel=INFO --workdir=$VIRTUAL_ENV 1> /dev/null &) && \
    sleep 7 && \
    (if [ -n "$EXTERNAL_IP" ] ; then \
      inveniomanage config set CFG_SITE_SECURE_URL http://"$EXTERNAL_IP":4000; \
     else \
      inveniomanage config set CFG_SITE_SECURE_URL http://0.0.0.0:4000; \
     fi) && \
    inveniomanage runserver && \
    bash

# TODO replace CMD with `CMD honcho start`
